Repository kubernetes-sigs/community-images, pull requests merged in 2023-03, with the labels that each got.

#36 Update git references
  Makefile
  README.md
  cmd/community_images/cli/header.go
  cmd/community_images/cli/root.go
  cmd/community_images/main.go
  deploy/.goreleaser.yaml
  deploy/krew/community_images.yaml
  go.mod
Labels: cncf-cla: yes, size/M, lgtm, approved

#40 fix invalid module name
  go.mod
Labels: cncf-cla: yes, size/XS, lgtm, approved

#41 update fatih/color and minio/pkg
  go.mod
  go.sum
Labels: cncf-cla: yes, size/XS, approved

#49 fix github owner/org
  deploy/.goreleaser.yaml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#52 .github/workflows: run go mod tidy when a PR is opened
  .github/workflows/go.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#53 .github/workflows: Add permission for contents
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, lgtm, approved

#54 update OWNERS file
  OWNERS
Labels: cncf-cla: yes, size/XS, lgtm, approved

#57 fix ParseImageName
  pkg/community_images/image_name.go
  pkg/community_images/image_name_test.go
Labels: cncf-cla: yes, size/S, lgtm, approved

#58 Update README.md
  README.md
Labels: cncf-cla: yes, size/XS, lgtm, approved
